# Generated by Django 3.0.5 on 2020-05-06 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.TextField(max_length=50)),
                ('category', models.TextField(max_length=300)),
                ('ingredients', models.TextField(max_length=500)),
                ('nutriscore', models.TextField(blank=True, max_length=50, null=True)),
                ('store', models.TextField(max_length=100, null=True)),
                ('link', models.TextField(max_length=100, null=True)),
                ('image_product', models.TextField(max_length=100, null=True)),
                ('image_ingredients', models.TextField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Aliments',
                'verbose_name_plural': 'Aliments',
            },
        ),
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='off.Food')),
                ('substitut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitut', to='off.Food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Substitut utilisateur',
                'verbose_name_plural': 'Substitut utilisateur',
            },
        ),
    ]
