# Generated by Django 3.0.5 on 2020-05-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('off', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Formulaire de contact',
                'verbose_name_plural': 'Formulaire de contact',
            },
        ),
    ]
